In [19]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

CREATING DATAFRAME

In [20]:
try:
    file_path = "../data/raw/EV Data Explorer 2025.xlsx"
    
    df = pd.read_excel(file_path,sheet_name="GEVO_EV_2025")
    
    print("Data Loaded Successfully")

except:
    print("File not found")

Data Loaded Successfully

In [21]:
#Printing top 10 rows

df.head(5)

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World


DATASET OVERVIEW

In [22]:
print("Shape:")

print(df.shape)

Shape:
(16436, 9)

In [23]:
print("Columns:")

print(df.columns.tolist())

Columns:
['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year', 'unit', 'value', 'Aggregate group']

In [24]:
print("info")

print(df.info())

info
<class 'pandas.DataFrame'>
RangeIndex: 16436 entries, 0 to 16435
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   16436 non-null  str
 1   category         16436 non-null  str
 2   parameter        16436 non-null  str
 3   mode             16436 non-null  str
 4   powertrain       16436 non-null  str
 5   year             16436 non-null  int64
 6   unit             16436 non-null  str
 7   value            16436 non-null  float64
 8   Aggregate group  16436 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 1.1 MB
None

In [25]:
print("Duplicate Rows:")

print(df.duplicated().sum())

Duplicate Rows:
12

UNDERSTANDING DATA CONTENT

In [26]:
print("Number of Countries:")

print(df["region_country"].nunique())

Number of Countries:
63

In [27]:
print("Number of Parameters:")

print(df["parameter"].nunique())

print(df["parameter"].value_counts())

Number of Parameters:
9
parameter
EV stock                         4573
EV sales                         4306
EV sales share                   2502
EV stock share                   2414
EV charging points                899
Oil displacement, million lge     563
Oil displacement Mbd              563
Battery demand                    557
Electricity demand                 59
Name: count, dtype: int64

In [28]:
print(df["category"].value_counts())

category
Historical          14616
Projection-STEPS     1820
Name: count, dtype: int64

In [29]:
print(df['mode'].value_counts())

mode
Cars                5370
2 and 3 wheelers    2928
Vans                2921
Buses               2695
Trucks              1623
EV                   899
Name: count, dtype: int64

In [30]:
print(df['powertrain'].value_counts())

powertrain
EV                         6658
BEV                        4917
PHEV                       2394
FCEV                       1568
Publicly available slow     465
Publicly available fast     434
Name: count, dtype: int64

In [31]:
print("Year Coverage:")

print(
    df.groupby("category")["year"]
      .agg(["min", "max"])
)

Year Coverage:
                   min   max
category
Historical        2010  2024
Projection-STEPS  2020  2030

In [32]:
# Removing duplicates

df = df.drop_duplicates()

In [33]:
# Standardizing column names

df.columns = (

    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year',
       'unit', 'value', 'aggregate_group'],
      dtype='str')

In [34]:
df.head(5)

,region_country,category,parameter,mode,powertrain,year,unit,value,aggregate_group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World

SAVING CLEAN DATA

In [35]:
df.to_csv(
    "../data/processed/ev_clean_dataset_2025.csv",
    index=False
)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.