In [2]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

LOADING WORKBOOK

In [3]:
file_path = "../data/raw/EV Data Explorer 2025.xlsx"

Excel_sheets = pd.ExcelFile(file_path)

print(Excel_sheets.sheet_names)

['GEVO_EV_2025', 'Notes', 'Examples >>', 'EV sales countries', 'EV sales macro regions', 'Other than sales and stock', 'Regions and countries']

READING MAIN SHEET FROM WORKBOOK

In [4]:
data_frame = pd.read_excel(file_path, sheet_name="GEVO_EV_2025")

DATA STRUCTURE AND USEFUL INFORMATION

In [9]:
print(data_frame.shape)

print(data_frame.info())

(16436, 9)
<class 'pandas.DataFrame'>
RangeIndex: 16436 entries, 0 to 16435
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   16436 non-null  str
 1   category         16436 non-null  str
 2   parameter        16436 non-null  str
 3   mode             16436 non-null  str
 4   powertrain       16436 non-null  str
 5   year             16436 non-null  int64
 6   unit             16436 non-null  str
 7   value            16436 non-null  float64
 8   Aggregate group  16436 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 1.1 MB
None

In [10]:
data_frame.head()

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World

CHECKING DUPLICATE RECORDS

In [11]:
duplicates = data_frame.duplicated().sum()

print(f'Duplicate rows count : {duplicates}')

Duplicate rows count : 12

EXPLORING SOME USEFUL COLUMNS

In [16]:
columns  = ['region_country', 'category', 'parameter', 'powertrain']

In [ ]:
print(data_frame[i].value_counts() for i in columns )

region_country
World                1124
Europe               1106
China                 952
Rest of the world     919
USA                   746
                     ...
Croatia                18
Seychelles             18
Cyprus                 17
Uzbekistan             16
Jordan                  8
Name: count, Length: 63, dtype: int64
category
Historical          14616
Projection-STEPS     1820
Name: count, dtype: int64
parameter
EV stock                         4573
EV sales                         4306
EV sales share                   2502
EV stock share                   2414
EV charging points                899
Oil displacement, million lge     563
Oil displacement Mbd              563
Battery demand                    557
Electricity demand                 59
Name: count, dtype: int64
powertrain
EV                         6658
BEV                        4917
PHEV                       2394
FCEV                       1568
Publicly available slow     465
Publicly available fast     434
Name: count, dtype: int64

In [19]:
data_frame["region_country"].nunique()

63

In [25]:
print("Year Coverage:")

data_frame.groupby("category")["year"].agg(["min", "max"])

Year Coverage:

                   min   max
category
Historical        2010  2024
Projection-STEPS  2020  2030

RESTRUCTURING COLUMN NAMES

In [26]:
data_frame.columns = (

    data_frame.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

data_frame.columns

Index(['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year',
       'unit', 'value', 'aggregate_group'],
      dtype='str')

SAVING CLEAN DATA

In [27]:
data_frame.to_csv(
    "../data/processed/ev_clean_dataset_2025.csv",
    index=False
)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.