In [13]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [14]:
#pip install openpyxl

In [5]:
file_path = "../data/raw/EV Data Explorer 2026.xlsx"

df = pd.read_excel(file_path,sheet_name="GEVO_EV_2026")

print("Data Loaded Successfully")

Data Loaded Successfully

In [6]:
print("rows, columns:")
print(df.shape)

rows, columns:
(49176, 9)

In [7]:
df.head(10)

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,Chile,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,1.0,Other
1,Norway,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,18.0,Other
2,Portugal,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,6.0,Other
3,Canada,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,2.0,Other
4,Chile,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,4.0,Other
5,France,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,9.0,Other
6,Germany,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,18.0,Other
7,Italy,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,1.0,Other
8,Netherlands,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,21.0,Other
9,Norway,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,58.0,Other

In [8]:
print(df.columns.tolist())

['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year', 'unit', 'value', 'Aggregate group']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49176 entries, 0 to 49175
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   48098 non-null  str
 1   category         49176 non-null  str
 2   parameter        49176 non-null  str
 3   mode             49176 non-null  str
 4   powertrain       49176 non-null  str
 5   year             49176 non-null  int64
 6   unit             26594 non-null  str
 7   value            49176 non-null  float64
 8   Aggregate group  49176 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 3.4 MB

In [15]:
df.describe(include="object")

,region_country,category,parameter,mode,powertrain,unit,Aggregate group
count,48098,49176,49176,49176,49176,26594,49176
unique,72,3,19,13,10,9,6
top,China,Historical,EV stock,Cars,EV,Vehicles,Other
freq,2841,47915,7816,7872,15305,15397,31536

In [18]:
missing = df.isnull().sum()

print(missing)

region_country      1078
category               0
parameter              0
mode                   0
powertrain             0
year                   0
unit               22582
value                  0
Aggregate group        0
dtype: int64

In [20]:
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
15

In [22]:
print("Number of Countries/Regions:")
print(df["region_country"].nunique())

df["region_country"].unique()[:20]

Number of Countries/Regions:
72

<StringArray>
[         'Chile',         'Norway',       'Portugal',         'Canada',
         'France',        'Germany',          'Italy',    'Netherlands',
    'Switzerland',        'Belgium',        'Denmark',        'Finland',
          'Spain', 'United Kingdom',         'Greece',        'Iceland',
         'Poland',         'Sweden',      'Australia',         'Mexico']
Length: 20, dtype: str

In [23]:
df["category"].value_counts()

category
Historical          47915
Projection-STEPS      640
Projection-CPS        621
Name: count, dtype: int64

In [24]:
print("Number of Parameters:")
print(df["parameter"].nunique())

sorted(df["parameter"].unique())

Number of Parameters:
19

['Average capacity per EV',
 'Average capacity per EVSE',
 'Battery deployment',
 'EV charging points',
 'EV sales',
 'EV sales share',
 'EV stock',
 'EV stock share',
 'Electric LDVs per charging point',
 'Electricity demand',
 'Oil displacement Mlge',
 'Oil displacement, Mbd',
 'price_mean_2025USD',
 'price_p0_2025USD',
 'price_p100_2025USD',
 'price_p25_2025USD',
 'price_p50_2025USD',
 'price_p75_2025USD',
 'price_p95_2025USD']

In [25]:
df["mode"].value_counts()

mode
Cars                 7872
All cars             5964
2 and 3 wheelers     4615
Vans                 4321
Buses                3955
Medium car           3780
Large car            3465
Small SUV/Pick-up    3325
City car             3073
Large SUV/Pick-up    2975
Trucks               2575
EV                   1804
EVSE                 1452
Name: count, dtype: int64

In [26]:
df["powertrain"].value_counts()

powertrain
EV                               15305
BEV                              11526
ICEV                              9268
PHEV                              7750
FCEV                              1621
ALL                               1568
EREV                               686
Publicly available slow            575
Publicly available fast            546
Publicly available ultra-fast      331
Name: count, dtype: int64

In [27]:
print("Minimum Year:", df["year"].min())
print("Maximum Year:", df["year"].max())

print("\nNumber of Years:")
print(df["year"].nunique())

Minimum Year: 2010
Maximum Year: 2035

Number of Years:
17

In [28]:
df["unit"].value_counts()

unit
Vehicles                              15397
percent                                5557
charging points                        1452
GWh                                    1140
Million litres gasoline equivalent      622
Million barrels per day                 622
kW/EVSE                                 602
vehicles                                601
kW/EV                                   601
Name: count, dtype: int64

In [30]:
df[df['unit'].isna()].head(20)

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
20578,Australia,Historical,price_p0_2025USD,City car,BEV,2010,NaN,41000.0,Other
20579,Australia,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,11000.0,Other
20580,Australia,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,29000.0,Other
20581,Australia,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,11000.0,Other
20582,Australia,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,19000.0,Other
20583,Brazil,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,9600.0,Other
20584,Brazil,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,27000.0,Other
20585,Brazil,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2010,NaN,56000.0,Other
20586,Brazil,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,11000.0,Other
20587,Brazil,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,21000.0,Other
20588,Canada,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,13000.0,Other
20589,Canada,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,24000.0,Other
20590,Canada,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,13000.0,Other
20591,Canada,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,17000.0,Other
20592,China,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,3400.0,Projection_country
20593,China,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,16000.0,Projection_country
20594,China,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2010,NaN,12000.0,Projection_country
20595,China,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,7300.0,Projection_country
20596,China,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,8000.0,Projection_country
20597,France,Historical,price_p0_2025USD,City car,BEV,2010,NaN,48000.0,Other

In [31]:
df.groupby("parameter")["unit"].apply(lambda x: x.isna().sum())

parameter
Average capacity per EV                0
Average capacity per EVSE              0
Battery deployment                     0
EV charging points                     0
EV sales                               0
EV sales share                         0
EV stock                               0
EV stock share                         0
Electric LDVs per charging point       0
Electricity demand                     0
Oil displacement Mlge                  0
Oil displacement, Mbd                  0
price_mean_2025USD                  3226
price_p0_2025USD                    3226
price_p100_2025USD                  3226
price_p25_2025USD                   3226
price_p50_2025USD                   3226
price_p75_2025USD                   3226
price_p95_2025USD                   3226
Name: unit, dtype: int64

In [32]:
df.groupby("category")["year"].agg(["min", "max"])

                   min   max
category
Historical        2010  2025
Projection-CPS    2035  2035
Projection-STEPS  2035  2035

In [33]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [34]:
df.columns

Index(['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year',
       'unit', 'value', 'aggregate_group'],
      dtype='str')

In [37]:
df[df["region_country"].isna()].head(20)

,region_country,category,parameter,mode,powertrain,year,unit,value,aggregate_group
20631,NaN,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,4900.0,Other
20632,NaN,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,8500.0,Other
20633,NaN,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2010,NaN,26000.0,Other
20634,NaN,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,4900.0,Other
20635,NaN,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,7200.0,Other
20713,NaN,Historical,price_p0_2025USD,City car,BEV,2011,NaN,45000.0,Other
20714,NaN,Historical,price_p0_2025USD,City car,ICEV,2011,NaN,4800.0,Other
20715,NaN,Historical,price_p0_2025USD,Large car,ICEV,2011,NaN,22000.0,Other
20716,NaN,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2011,NaN,26000.0,Other
20717,NaN,Historical,price_p0_2025USD,Medium car,ICEV,2011,NaN,4800.0,Other
20718,NaN,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2011,NaN,7700.0,Other
20809,NaN,Historical,price_p0_2025USD,City car,BEV,2012,NaN,43000.0,Other
20810,NaN,Historical,price_p0_2025USD,City car,ICEV,2012,NaN,4900.0,Other
20811,NaN,Historical,price_p0_2025USD,Large car,ICEV,2012,NaN,21000.0,Other
20812,NaN,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2012,NaN,25000.0,Other
20813,NaN,Historical,price_p0_2025USD,Medium car,BEV,2012,NaN,28000.0,Other
20814,NaN,Historical,price_p0_2025USD,Medium car,ICEV,2012,NaN,5000.0,Other
20815,NaN,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2012,NaN,7200.0,Other
20921,NaN,Historical,price_p0_2025USD,City car,BEV,2013,NaN,40000.0,Other
20922,NaN,Historical,price_p0_2025USD,City car,ICEV,2013,NaN,4900.0,Other

In [38]:
df[df["region_country"].isna()]["parameter"].value_counts()

parameter
price_p0_2025USD      154
price_p100_2025USD    154
price_p25_2025USD     154
price_p50_2025USD     154
price_p75_2025USD     154
price_p95_2025USD     154
price_mean_2025USD    154
Name: count, dtype: int64

In [39]:
df[df["region_country"].isna()]["aggregate_group"].value_counts()

aggregate_group
Other    1078
Name: count, dtype: int64