In [1]:
import pandas as pd

import warnings

warnings.filterwarnings("ignore")

LOADING CLEANED DATASET

In [4]:
try:
    file_path = "../data/processed/ev_clean_dataset_2025.csv"
    
    df = pd.read_csv(file_path)
    
    print("Data Loaded Successfully")

except:
    print("File not found")

Data Loaded Successfully

In [5]:
df.head(5)

,region_country,category,parameter,mode,powertrain,year,unit,value,aggregate_group
0,World,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,170000000.0,_World
1,World,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,150000000.0,_World
2,China,Projection-STEPS,EV stock,2 and 3 wheelers,BEV,2030,Vehicles,91000000.0,Other
3,China,Projection-STEPS,EV stock,Cars,BEV,2030,Vehicles,82000000.0,Other
4,World,Projection-STEPS,EV stock,Cars,PHEV,2030,Vehicles,82000000.0,_World

In [6]:
df["region_country"].nunique()

63

In [10]:
sorted(df["region_country"].unique())

['Africa',
 'Asia Pacific',
 'Australia',
 'Austria',
 'Belgium',
 'Brazil',
 'Bulgaria',
 'Canada',
 'Central and South America',
 'Chile',
 'China',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EU27',
 'Estonia',
 'Europe',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Jordan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Malaysia',
 'Mexico',
 'Middle East and Caspian',
 'Netherlands',
 'New Zealand',
 'North America',
 'Norway',
 'Poland',
 'Portugal',
 'Rest of the world',
 'Romania',
 'Russia',
 'Seychelles',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Spain',
 'Sweden',
 'Switzerland',
 'Thailand',
 'Turkiye',
 'USA',
 'United Kingdom',
 'Uzbekistan',
 'Viet Nam',
 'World']

DELETING DATA WHICH IS NOT RELATED TO COUNTRIES AND CREATING A DATAFRAME

In [11]:
not_countries = [
    "World",
    "Africa",
    "Asia Pacific",
    "Central and South America",
    "EU27",
    "Europe",
    "Middle East and Caspian",
    "North America",
    "Rest of the world"
]

In [12]:
country_df = df[
    ~df["region_country"].isin(not_countries)
].copy()

In [13]:
ev_sales_df = country_df[
    (country_df["category"] == "Historical") &
    (country_df["parameter"] == "EV sales")
].copy()

print(ev_sales_df.shape)
print(ev_sales_df["mode"].value_counts())
print(ev_sales_df["powertrain"].value_counts())

(2829, 9)
mode
Cars                1399
2 and 3 wheelers     463
Vans                 439
Buses                353
Trucks               175
Name: count, dtype: int64
powertrain
BEV     1763
PHEV     734
FCEV     332
Name: count, dtype: int64

In [14]:
model_df = country_df[
    (country_df["category"] == "Historical") &
    (country_df["parameter"] == "EV sales")
].copy()

In [15]:
print(model_df["region_country"].nunique())

print(sorted(model_df["year"].unique()))

print(model_df.duplicated().sum())

model_df.head()

53
[np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]
0

,region_country,category,parameter,mode,powertrain,year,unit,value,aggregate_group
73,China,Historical,EV sales,2 and 3 wheelers,BEV,2021,Vehicles,11000000.0,Other
107,China,Historical,EV sales,2 and 3 wheelers,BEV,2020,Vehicles,8200000.0,Other
110,China,Historical,EV sales,2 and 3 wheelers,BEV,2022,Vehicles,8000000.0,Other
116,China,Historical,EV sales,2 and 3 wheelers,BEV,2023,Vehicles,7800000.0,Other
121,China,Historical,EV sales,2 and 3 wheelers,BEV,2024,Vehicles,7200000.0,Other

In [18]:
country_year_df = (
    model_df
    .groupby(
        ["region_country", "year"],
        as_index=False
    )["value"]
    .sum()
)

print(country_year_df.shape)

country_year_df.head()

(668, 3)

  region_country  year   value
0      Australia  2011    49.0
1      Australia  2012   250.0
2      Australia  2013   290.0
3      Australia  2014  1320.0
4      Australia  2015  1760.0

In [19]:
country_year_df.describe()

              year         value
count   668.000000  6.680000e+02
mean   2017.817365  2.056932e+05
std       4.078267  1.366752e+06
min    2010.000000  1.000000e+00
25%    2015.000000  4.802500e+02
50%    2018.000000  4.675000e+03
75%    2021.000000  3.617425e+04
max    2024.000000  1.908186e+07

In [20]:
country_year_df.groupby("region_country").size().describe()

count    53.000000
mean     12.603774
std       3.040367
min       2.000000
25%      10.000000
50%      14.000000
75%      15.000000
max      15.000000
dtype: float64

In [ ]:
country_counts = (
    country_year_df
    .groupby("region_country")
    .size()
    .sort_values()
)

print(country_counts)

region_country
Uzbekistan         2
Croatia            6
Luxembourg         6
Cyprus             6
Slovenia           9
Seychelles         9
Czech Republic    10
Bulgaria          10
Ireland           10
Lithuania         10
Hungary           10
Slovakia          10
Romania           10
Latvia            10
Estonia           10
Costa Rica        11
Viet Nam          11
South Africa      12
Indonesia         12
Russia            13
Greece            13
Malaysia          13
Austria           13
Turkiye           13
Colombia          14
Finland           14
Australia         14
Chile             14
Mexico            14
Switzerland       14
Brazil            15
Denmark           15
Israel            15
Italy             15
Japan             15
Korea             15
France            15
Germany           15
India             15
Iceland           15
China             15
Canada            15
Belgium           15
Poland            15
Netherlands       15
Portugal          15
New Zealand       15
Norway            15
Thailand          15
Sweden            15
Spain             15
USA               15
United Kingdom    15
dtype: int64

REMOVING DATA WHICH IS HAVING DATA BELOW 10 YEARS

THERE IS NO UNIVERSAL RULE BUT 10 YEARS IS A COMMON THRESHOLD BECAUSE

ADOPTION PROCESS UNFOLD SLOWLY

IF ONLY FEW COUNTRIES HAVE LESS DATA , THEY BEHAVE LIKE OUTLIERS AND CAN DISTORT MODEL TRAINING

In [25]:
country_counts = country_year_df.groupby("region_country").size()

valid_countries = country_counts[country_counts >= 10].index

model_df = country_year_df[country_year_df["region_country"].isin(valid_countries)].copy()

In [23]:
print(model_df.shape)

print(model_df["region_country"].nunique())

print(model_df["year"].min(), model_df["year"].max())

(630, 3)
47
2010 2024

In [24]:
model_df["value"].describe()

count    6.300000e+02
mean     2.179017e+05
std      1.406498e+06
min      1.000000e+00
25%      5.485000e+02
50%      5.330000e+03
75%      4.184075e+04
max      1.908186e+07
Name: value, dtype: float64

In [26]:
model_df.to_csv(
    "../data/processed/eda_ev_dataset.csv",
    index=False
)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.